version: '3.8'
services:
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=test123
      - ACCEPT_EULA=Y
      - MSSQL_DB=mydb
    ports:
      - 1433:1433
#docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=test123" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest
#docker run --name SQLServer -d -p 1433:1433 -e sa_password=test123 -e ACCEPT_EULA=Y mcr.microsoft.com/mssql/server:2019-latest

docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=test123" -p 1433:1433 --name sql2 --hostname localhost -d mcr.microsoft.com/mssql/server:2019-latest

docker exec -it sql2 "bash"

/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "test123"
